# Generated by Django 3.2.5 on 2021-07-13 03:53

from django.db import migrations, models
import django_dropbox_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(storage=django_dropbox_storage.storage.DropboxStorage(), upload_to='projects/img/'),
        ),
    ]
